// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

//A class from the firebase_core package that represents the configuration options for Firebase services.
/*
defaultTargetPlatform, kIsWeb, TargetPlatform:
Dart and Flutter classes that help determine the target platform for the application.*/
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

//methods and constants for obtaining Firebase configuration options based on the platform.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

// Platform-Specific Configuration Options:
/*For each platform (Web, Android, iOS, macOS), there are constants (web, android, ios, macos)
containing FirebaseOptions with specific configuration settings
like API key, app ID, messaging sender ID, project ID, database URL, and storage bucket */
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZtkiqZ9kvxe-6SpIr-sJcGkzPVlstUjE',
    appId: '1:964272040303:web:39398a880de6e4fb8da09a',
    messagingSenderId: '964272040303',
    projectId: 'jarking-firebase',
    authDomain: 'jarking-firebase.firebaseapp.com',
    databaseURL:
        'https://jarking-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jarking-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrGcHq6qFRefp81_FR4gD_u1ueruGw8JY',
    appId: '1:964272040303:android:3ab79cb6490f10d68da09a',
    messagingSenderId: '964272040303',
    projectId: 'jarking-firebase',
    databaseURL:
        'https://jarking-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jarking-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzxp8ZHFWiPNBiIOqEPKZgluMyYc1Ridk',
    appId: '1:964272040303:ios:fea2c044e2d3a3708da09a',
    messagingSenderId: '964272040303',
    projectId: 'jarking-firebase',
    databaseURL:
        'https://jarking-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jarking-firebase.appspot.com',
    iosBundleId: 'com.example.finalProjectForFlutterByJarling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzxp8ZHFWiPNBiIOqEPKZgluMyYc1Ridk',
    appId: '1:964272040303:ios:761b8b320984442f8da09a',
    messagingSenderId: '964272040303',
    projectId: 'jarking-firebase',
    databaseURL:
        'https://jarking-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jarking-firebase.appspot.com',
    iosBundleId: 'com.example.finalProjectForFlutterByJarling.RunnerTests',
  );
}
